site_name: Mojito
site_description: Mojito framework. Fresh, fast, and simple web framework for building HTML-first websites
site_url: https://abauman97.github.io/Mojito/
repo_url: https://github.com/abauman97/Mojito

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: cyan

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: cyan

  features:
    - content.code.copy

plugins:
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Features: features.md
  - Getting Started: getting_started.md
  - Routing: routing.md
  - Auth: auth.md
  - Forms: forms.md
  - Message Flashing: message_flashing.md
  - Configuration: configuration.md
  - Experimental:
    - templates.md
